In [17]:
print("ola mundo")

ola mundo


In [2]:
# Importando bibliotecas essenciais
import numpy as np                  # Trabalhar com arrays e operações matemáticas
import pandas as pd                # Manipulação de dados com DataFrames
import seaborn as sns              # Gráficos estatísticos e bonitos

# Configurando o ambiente para exibição de gráficos no Jupyter Notebook

sns.set(style='whitegrid')        # Define um estilo limpo para os gráficos
pd.set_option('display.max_columns', None)  # Exibe todas as colunas de DataFrames

print("Ambiente configurado e bibliotecas importadas!")

Ambiente configurado e bibliotecas importadas!


In [3]:
# Importando bibliotecas adicionais para visualização e manipulação de dados
import matplotlib.pyplot as plt    

# Configurando o matplotlib para exibir gráficos inline no Jupyter Notebook
%matplotlib inline                


print("Ambiente configurado e bibliotecas importadas!")

Ambiente configurado e bibliotecas importadas!


In [4]:
import numpy as np

#Criar um array numpy unidimensional
lista = [10, 20, 30, 40, 50]
array = np.array(lista) # Converte a lista em um array numpy através da função np.array()

# Pode ser criado de forma direta
arrayOutro = np.array([10, 20, 30, 40, 50])

print("Array unidimensional:", array)
print("Tipo do array:", type(array))

Array unidimensional: [10 20 30 40 50]
Tipo do array: <class 'numpy.ndarray'>


In [5]:
# Exemplos de Operações com arrays numpy
# Utilizando a lista do tipo numpy no bloco acima "array"

# Exibindo Array numpy
print("Array:", array) # Exibe o array numpy

# Soma de todos os elementos do array
print("Soma de todos os elementos:", np.sum(array)) # função sum do numpy é que soma todos os elementos do array

# Fazendo a media dos elementos do array
print("Média dos elementos:", np.mean(array)) # função mean do numpy é que calcula a media dos elementos do array

# Multiplicando todos os elementos do array por 2

print("Array multiplicado por 2:", array * 2) # Multiplicando todos os elementos do array por 2

# Tambem pode-se fazer a multiplicação com a função do numpy
print("Array multiplicado por 2 com função:", np.multiply(array, 2)) # Função multiply do numpy é que multiplica todos os elementos do array por 2 (ListaDoTipoNumpy * numero de desejado)



Array: [10 20 30 40 50]
Soma de todos os elementos: 150
Média dos elementos: 30.0
Array multiplicado por 2: [ 20  40  60  80 100]
Array multiplicado por 2 com função: [ 20  40  60  80 100]


In [6]:
# Criando uma array bidimensional (matriz)
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matriz:\n", matriz) # Exibe a matriz numpy

Matriz:
 [[1 2 3]
 [4 5 6]]


In [10]:
# Acessar arrays utilizando a indexação e slicing

# Utilizando o array bidimensional (matriz) do bloco acima

# Exibindo o array numpy bidimensional
print("Array:")
print(matriz) # Exibe o array numpy bidimensional

# Indexação: acessando elementos da linha 1 e coluna 2
print("Elemento na linha 1, coluna 2:", matriz[1, 2]) # Acessa o elemento na linha 1 e coluna 2 da matriz numpy

# Slicing: acessando a primeira linha da matriz
print("Primeira linha:", matriz[0, 0:3]) # Acessa a primeira linha da matriz numpy (linha 0) e todas as colunas (0:3)

Array:
[[1 2 3]
 [4 5 6]]
Elemento na linha 1, coluna 2: 6
Primeira linha: [1 2 3]


In [17]:
#Exemplo de broadcasting com numpy

# Essa aplicação é utilizada para operações entre arrays de diferentes dimensões

# Criando um vetor
vetor = np.array([10, 20, 30])

# Somando o vetor a cada linha da matriz
resultado = matriz + vetor

print("\nResultado do broadcasting (matriz + vetor):")
print(resultado)


Resultado do broadcasting (matriz + vetor):
[[11 22 33]
 [14 25 36]]
